### ISSUE TITLE
Enhance xt.input attribute 

### ISSUE THREAD

**Issue by anirudh-hegde** [dot-agent/nextpy#122]
```
def index() -> xt.Component:
    layout = xt.form(xt.vstack(
        xt.input(
            placeholder="Paste YAML code here",
            on_change=State.on_yaml_input_change,
            width="30%",
            height="300px",
        ), ),
        xt.button("Convert to Python", on_click=State.handle_conversion),
        xt.text(State.python_data, font_size="2em"),
        spacing="1em",
        align_items="center",
        justify_content="center",
        height="100vh",
    )
    return layout

```
### Problem statement
when I type inside the input it shows 
![image](https://github.com/dot-agent/nextpy/assets/105560839/e6de444c-af94-46cd-a052-9ebc148c5067)

### Feature
When I press enter it should go to next line

**Comment by anubrag** [comment]
Hey Anirud,

For handling larger text inputs like YAML code,  we can use `xt.text_area` a better fit. Here's a quick example to show how it can be set up:

```python
xt.text_area(
    placeholder="Paste YAML code here",
    on_change=State.on_yaml_input_change,
    width="30%",
    height="300px",
)
```

By the way, I'm currently working on putting together more detailed documentation for these components, including `text_area`. It's a work in progress, but you can check out what I've got so far [here](https://github.com/dot-agent/nextpy/blob/main/docs/references/frontend/components/chakra/forms/textarea_reference.md). I'm planning to get the form-related docs polished up first.

**Comment by anirudh-hegde** [comment]
Thank you, it's working :)
