### ISSUE TITLE
When I click on image, it's not opening the link

### ISSUE THREAD

**Issue by anirudh-hegde** [dot-agent/nextpy#128]
```
xt.button(
                # xt.link("https://github.com/anirudh-hegde", ),
                # on_click=lambda : open_github),
                xt.image(
                    src="/github.svg",
                    height="30px",
                    width="30px",
                    padding_right='1px',
                    target="https://github.com/anirudh-hegde"
                ),
            ),
```

**Comment by Raj4646** [comment]
Wrap the xt.image component inside a xt.link component and use "href" prop for the xt.link component. 
`xt.link(
             xt.image(
                    src="/github.svg",
                    height="30px",
                    width="30px",
                    padding_right='1px',),
href="https://github.com/anirudh-hegde",
)`
