### ISSUE TITLE
Unknown instruction CMD["nextpy","init","&&","nextpy","run"]

### ISSUE THREAD

**Issue by anirudh-hegde** [dot-agent/nextpy#134]
FROM python:3.8-alpine
WORKDIR /app
COPY Casper.py .
COPY requirements.txt .
RUN pip install -r requirements.txt
CMD["nextpy","init","&&","nextpy","run"]

When I try to build, it shows the error: ERROR: failed to solve: dockerfile parse error on line 7: unknown instruction: CMD["nextpy","run"]

**Comment by anirudh-hegde** [comment]
> FROM python:3.8-alpine WORKDIR /app COPY Casper.py . COPY requirements.txt . RUN pip install -r requirements.txt CMD["nextpy","init","&&","nextpy","run"]
> 
> When I try to build, it shows the error: ERROR: failed to solve: dockerfile parse error on line 7: unknown instruction: CMD["nextpy","run"]

Somebody please reply

**Comment by anirudh-hegde** [comment]
Somebody please reply

**Comment by tianyax** [comment]
This shouldn't be a `nextpy` problem, from your description it should be a `Dockerfile` syntax mistake..
Change line 6 to `CMD ["nextpy", "init", "&&", "nextpy", "run"]` and try again.

**Comment by tianyax** [comment]
> > This shouldn't be a `nextpy` problem, from your description it should be a `Dockerfile` syntax mistake.. Change line 6 to `CMD ["nextpy", "init", "&&", "nextpy", "run"]` and try again.
> 
> Can you please explain how your syntax differs from my syntax

@anirudh-hegde `CMD` requires a space to distinguish that this is a keyword recognized by the `Dockerfile`. Just from the description looks like this

**Comment by anirudh-hegde** [comment]
> > > This shouldn't be a `nextpy` problem, from your description it should be a `Dockerfile` syntax mistake.. Change line 6 to `CMD ["nextpy", "init", "&&", "nextpy", "run"]` and try again.
> > 
> > 
> > Can you please explain how your syntax differs from my syntax
> 
> @anirudh-hegde `CMD` requires a space to distinguish that this is a keyword recognized by the `Dockerfile`. Just from the description looks like this

Will try to execute

**Comment by anirudh-hegde** [comment]
Thank you, @tianyax, it's working
